name: Bot Classificador de CVs
on:
  schedule:
    # 0 -> minut 0
    # 7 -> hora 7 (en format UTC)
    # * -> qualsevol dia del mes
    # * -> qualsevol mes
    # 1 -> dilluns (Monday)
    - cron: '0 7 * * 1'  
  workflow_dispatch:       # Això et permet seguir executant-lo a mà quan vulguis provar-ho

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Descarregar codi
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instal·lar llibreries
        run: |
          pip install -r requirements.txt

      - name: Executar Script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python main.py
